Issue 14 hide author option
encorelab/ck-board pull request #116
Opened 2021-12-08 15:31 UTC by l3n0ire

## Details

- Added option in add-board and configuration-modal to hide author names
- When "show author names" is unchecked, author names will appear as Anonymous to other students
- Teacher can still see all author names

Closes #14

2021-12-15 18:29 UTC, JoelWiebe requested changes
Adding separate hide options for teacher and students is a good idea. 

Adding these to the permissions tab makes sense. Good labels for each option.

For some reason, as a teacher, the canvas continues to show Anonymous on my old posts, but when I open them up I can see the author (i.e., see the Test 1 post below). Permission are set so that both students and teachers should be able to see the author names. Any idea why this might be happening? 

![image](https://user-images.githubusercontent.com/6416247/146243908-24a9a4a9-df61-4991-a928-3c0af6607e87.png)

2021-12-15 19:19 UTC, l3n0ire commented
So when the canvas loads it uses PostService(which gets the posts from firebase) to get the existing fabric objects and renders them. So somehow the fabric js object for Test1 and Test2 had the author text field saved as Anonymous, but the actual author is still correct (ex JoelWeibe).  So thats why the author name shows up in the expanded post modal. I could add in a function to update the author text fields to reflect the permission. Right now it only updates to anonymous when "show author name" is unchecked, but doesn't do anything if "show author name" is checked

2021-12-20 15:52 UTC, JoelWiebe commented
Thanks @l3n0ire, that sounds like a great idea to update author names when show author name is checked, to ensure all author names are shown again after being anonymized. Let's try that, then I'll do a quick review again.

2022-01-03 20:13 UTC, Ammar-T commented
I tried hiding author names for teachers, however the names don't become "Anonymous" on the fabric post until I refresh the page. Could you try to update it so the change takes effect immediately without having to refresh? @l3n0ire

2022-01-03 20:16 UTC, Ammar-T commented on src/app/components/canvas/canvas.component.ts
> +          if(!((this.user.role =="student" && this.board.permissions.showAuthorName) || this.user.role =="teacher")){
Can you extract this logic into smaller chunks, similar to my suggestions in the locking PR?

2022-01-06 20:39 UTC, JoelWiebe commented
Great work!

Tested:
- Teacher toggles anonymity of authors for teachers
- Teacher toggles anonymity of authors for students

Logged in on two teacher accounts and one student account

- When T1 made a change to anonymity for teachers, effect was immediate for T1, but T2 had to refresh their browser for changes to take effect
- When T1 made a change to anonymity for students, S1 how to refresh their browser for changes to take effect

Is it easy to make changes take immediate effect for other students and teachers too? If this is a bit of work, please don't worry, this should be quite sufficient for the time being as is!

2022-01-06 20:40 UTC, JoelWiebe approved these changes

2022-01-06 20:41 UTC, JoelWiebe commented
@StevenWuzz can you provide your review (accept/request changes) when you get a chance?

2022-01-06 22:34 UTC, l3n0ire commented
> Great work!
> 
> Tested:
> 
> * Teacher toggles anonymity of authors for teachers
> * Teacher toggles anonymity of authors for students
> 
> Logged in on two teacher accounts and one student account
> 
> * When T1 made a change to anonymity for teachers, effect was immediate for T1, but T2 had to refresh their browser for changes to take effect
> * When T1 made a change to anonymity for students, S1 how to refresh their browser for changes to take effect
> 
> Is it easy to make changes take immediate effect for other students and teachers too? If this is a bit of work, please don't worry, this should be quite sufficient for the time being as is!

@JoelWiebe I'll create a separate issue for this and work on it this week

2022-01-11 01:57 UTC, Ammar-T approved these changes
💯

2022-01-19 03:14 UTC, StevenWuzz approved these changes

2022-01-19 17:15 UTC, JoelWiebe commented
Thanks everyone!!

@l3n0ire Please feel free to Resolve Conflicts and Merge :)

2022-01-19 22:46 UTC, merged