Question Authoring PR Draft
encorelab/ck-board pull request #369
Opened 2022-09-15 00:40 UTC by LunarFang416

## Details

- Implemented Question Authoring functionality on top of teh existing post creation feature
- Open response type posts are the same as before (but with different message prompt)
- Users can now create multiple choice questions in board, with a minimum of 2 options upto 6 options with only 1 correct answer
- Editing Multiple choice posts is also possible. This utilizes the existing `add-post-modal`. Options can be edited by the teacher to decrease/increase the number of options, or change question title. 

Tests:
- Could not do much stress testing regarding socket updates, however changes to the backend were minute, so chances that breaks occur are very slim
- However, I still made sure to test basic operations like, creating post, deleting post, adding tags, removing tags, which were successful.

Closes #343

2022-09-15 19:05 UTC, JoelWiebe requested changes
This is sooo cool! I really like the work you did with "Check Answer" for a created post. That's a really neat way for students to experience taking the questions.

Suggestions:
 1. I'm sorry, I think I gave some unclear instructions. At board creation, where we have the two types of board, could we change "Multiple Choice" and "Open Response" to "Brainstorm board" and "Question Authoring"? 
 * Brainstorm would be the classic board with "title" and "message" fields in its posts
 * Question Authoring boards would have the option to create either Multiple Choice questions or open response questions when adding new posts to the board. 
<img width="348" alt="Screen Shot 2022-09-15 at 2 56 23 PM" src="https://user-images.githubusercontent.com/6416247/190486677-3d3eace8-cfc7-4af2-8b78-9b3941ec5c55.png">

 2. Can we choose between post types when creating a new post in a Question Authoring board? We could do this perhaps either of two ways. Maybe this could work something like the following: when the add post modal pops up, there is an option above the title for Multiple Choice or Open Response, clicking on the Multiple Choice shows (1) the title, (2) multiple choice question prompt (NEW to your design), and (3) multiple choice creation tool; clicking Open Response option essentially dynamically (1) hides the multiple choice tool and (2) changes the question prompt to the open response question prompt (as shown below). Multiple choice could be the default option.
<img width="400" alt="Screen Shot 2022-09-15 at 2 53 39 PM" src="https://user-images.githubusercontent.com/6416247/190486240-0c2c59dc-8d0c-455b-85de-a2229f9eb6e5.png">

<img width="401" alt="Screen Shot 2022-09-15 at 2 54 30 PM" src="https://user-images.githubusercontent.com/6416247/190486380-bd082adf-f912-496e-a3c3-2219a35468ac.png">

 3. I just noticed that the manage group icon is duplicated in the project dashboard -- probably from a merge at some point
<img width="466" alt="Screen Shot 2022-09-15 at 3 04 24 PM" src="https://user-images.githubusercontent.com/6416247/190488112-bf148927-e8f5-47de-a25a-a104e710795d.png">

Really great work! Sorry about the confusion. Is something like the above possible?

2022-09-19 15:21 UTC, LunarFang416 commented
@JoelWiebe Made the changes that you requested. Hopefully it works smoothly now. 👍

2022-09-20 03:56 UTC, JoelWiebe commented on frontend/src/app/components/post-modal/post-modal.component.ts
> +        this.snackbarService.queueSnackbar('Incorrect, Try Again.');
Maybe either "Incorrect. Try again." (with a period after "Incorrect") or "Incorrect, please try again" (keeping the comma after "Incorrect"

2022-09-20 04:07 UTC, JoelWiebe commented
@LunarFang416 This is simply amazing! Well done.

Really looking forward to trying this out in a classroom. I may pitch this to a teacher in a graduate level class too. 

1. Is there a way we could let students know the requirements for being able to submit a multiple choice question? For instance, could they receive an error if they (1) do not have enough multiple choice options, (2) forgot to select a correct answer, or (3) did not create a prompt? 

2. Also, could we make the question field required for question authoring board open response question prompts?

These are lower priority, so I'm happy to come back to these later if you don't have time to work on these right now.

2022-09-20 13:39 UTC, JoelWiebe commented
Oh yeah, I guess we can remove the console logs too. Thanks for adding those, they are very helpful for testing.

2022-09-23 13:42 UTC, LunarFang416 commented
@JoelWiebe Just added the validation for the inputs when creating a post in the question authoring boards.

2022-09-28 14:45 UTC, JoelWiebe approved these changes
Great work!

2022-10-26 21:06 UTC, JoelWiebe commented
@DCH25 @Ammar-T Would one of you have a quick chance to review this?

2022-10-27 03:02 UTC, Ammar-T commented on backend/src/models/Post.ts
> +  public postCreationType!: PostCreationType;
I think `contentType` would be a better name for this field.

2022-10-27 03:08 UTC, Ammar-T approved these changes
Just the small field renaming and this looks fine to merge.

2022-10-27 13:45 UTC, merged