Issue 379 board context type trace
encorelab/ck-board pull request #399
Opened 2022-11-10 01:54 UTC by DCH25

## Details

- Add new trace logs for board context and board type
- Haven't implemented trace logs for the "workspace" board context since posts cannot be created in the workspace as of yet

Closes #379

2022-11-11 21:21 UTC, JoelWiebe commented
@DCH25 Thanks for getting this done. Although we don't have generative tasks in the workspace, we do have peer review (e.g., tagging, commenting, and upvoting). 

We really should be better at demoing new features for one another at our meetings! Just in case you workspace is confusing:

1. You can create a task workspace (first need at least one group and at least one bucket)
<img width="662" alt="Screen Shot 2022-11-11 at 4 12 41 PM" src="https://user-images.githubusercontent.com/6416247/201431469-2af73e0f-be42-4870-b4ee-739897f

2. Click the play button in the Manage Workflows tab
<img width="666" alt="Screen Shot 2022-11-11 at 4 16 55 PM" src="https://user-images.githubusercontent.com/6416247/201431945-0b3efcab-e22d-4afa-964c-5ec80c625005.png">
22e25.png">

3. Then open the CK Workspace UI to access with the teacher or student assigned to the associated group to tag, comment, or upvote posts
<img width="533" alt="Screen Shot 2022-11-11 at 4 13 33 PM" src="https://user-images.githubusercontent.com/6416247/201431564-442c8639-f7d2-4274-a3a3-54b74a29eed3.png">

Perhaps you knew this all already, but I figured I would repeat here just in case. If you have any questions I would be happy to follow up with you or meet sometime to discuss further. If you've completed logging for peer review tasks already then let me know and I will begin my review.

2022-11-29 18:23 UTC, JoelWiebe requested changes
@DCH25 Thanks for setting these trace logs

Tested
 - Creating or modifying posts in brainstorm board logs BRAINSTORMING board type
 - Creating or modifying posts in authoring board logs QUESTION_AUTHORING board type
 - Creating or modifying posts in personal board logs PERSONAL_BOARD board context
 - Creating or modifying posts in shared board logs SHARED_BOARD board context

Suggestions:
 - The board type for personal boards says "PROJECT_PERSONAL" -- it should say "PERSONAL_BOARD"
 - The board type for regular canvases says "PROJECT_SHARED" -- can we change this to "COMMUNITY_BOARD"?
 - I realize we don't yet have posts being created in the CK Workspace but posts from other boards and buckets can be assigned as tasks where upvoting, commenting, and tagging from within the CK Workspace; is it possible to log "WORKSPACE" as the board context when modifying a post from the CK Workspace?

2022-12-14 21:09 UTC, Ammar-T approved these changes

2022-12-14 21:44 UTC, Ammar-T commented
Did the renaming of board context values. Adding workspace as the context is a bit more tricky, would require a bit more work and ideally in a separate PR as well.

2022-12-14 22:59 UTC, merged