Todo Item Description and View Modal Implemented
encorelab/ck-board pull request #454
Opened 2022-12-22 02:29 UTC by LunarFang416

## Details

- Todo Item Description field now added, which also supports links and formats accordingly
- Uncompleted Items can now only be marked as completed through the individual todo item view modal, where you must give a rating to complete a task
- Already completed tasks will show the completion quality in the todo item view modal
- Todo Item types also renamed as specified

Closes #421 , Closes #452

2022-12-22 02:55 UTC, JoelWiebe commented
@LunarFang416 Wow, you made quick work of this! Impressive. 

For some reason, I'm getting an error each time I try to create a new TODO item. Are you getting this as well?
<img width="430" alt="Screen Shot 2022-12-21 at 9 54 59 PM" src="https://user-images.githubusercontent.com/6416247/209045443-4b14b1c1-4d7c-4913-a27a-4548871b920f.png">

2022-12-22 02:57 UTC, JoelWiebe commented
P.S. This should overwrite the old item Types but still leave the other fields of old items, right? For some reason my previously created TODO items don't seem to be showing up either right now.

2022-12-22 03:11 UTC, LunarFang416 commented
@JoelWiebe I'm unable to recreate the error that you are getting for some reason. I was able to create todo items in a new board with no errors. Thats strange.

For the old todo items, they are causing errors since they don't contain the new added fields: description and completion quality.

2022-12-22 04:09 UTC, JoelWiebe commented
I tried on a new board using a teacher account, and somehow I'm still getting this error below when I initially load the TODO List modal, then the error in my previous message when creating a new item.
<img width="433" alt="Screen Shot 2022-12-21 at 11 02 38 PM" src="https://user-images.githubusercontent.com/6416247/209052981-2cd82168-6903-4e5b-bf4c-b787f3a215f3.png">

Are all of your changes in this commit? Is there anything else I could check?

2022-12-23 16:27 UTC, JoelWiebe commented
@LunarFang416 Thanks for figuring that out! Clearly I'm not sleeping enough again, haha. Yes, I should have tried creating a new project not a new board. Is there a way that this could fail more gracefully or that we could easily add the missing fields for existing projects (as we have an existing project that students will continue to use and build onto their TODOs)?

2022-12-28 20:27 UTC, LunarFang416 commented
@JoelWiebe I made the changes so that older todo lists wont cause problems. Please let me know if it works smoothly on your end.

2022-12-28 23:36 UTC, JoelWiebe commented
Brilliant! Great work

Tested:

 - TODOs can be opened in modal pop-up
 - Authors are listed as either the individual or the group name
 - TODO items can be created and edited with a description field that can include links
 - Items require a rating before being completed

Suggestions:

1. Can we add hyperlink styling to the task title for the personal and group tabs (so that students know these rows are clickable)

(see current task titles below)
<img width="674" alt="Screen Shot 2022-12-28 at 4 57 15 PM" src="https://user-images.githubusercontent.com/6416247/209876389-2834ef75-30a8-44be-a785-9495d20e0f0d.png">

2. Can we (a) re-order and (b) rename the select drop-down for marking as complete (e.g., N/A, Poor, Low, Moderate, Good, Excellent -- in that order)? 

(currently select drop-down list is not in the ordinal order)
<img width="231" alt="Screen Shot 2022-12-28 at 3 34 05 PM" src="https://user-images.githubusercontent.com/6416247/209869020-91602af7-54f4-4891-a28c-b6730f9b3d76.png">

3. Can we re-order the select drop-down for TODO types in the following order? (e.g., Content learning, Social-emotional learning, Classroom engagement, and Assigned class work) -- NOTE: I re-named that last one

(the current select drop-down list order is displayed below, can we replace this order with the above ordering)
<img width="292" alt="Screen Shot 2022-12-28 at 4 50 09 PM" src="https://user-images.githubusercontent.com/6416247/209875865-8d632fad-3d30-419b-b796-b225702bea9c.png">

2023-01-02 00:57 UTC, JoelWiebe commented
Awesome work. Everything looks great!

Sorry, I just remembered one small item: If an item is marked as done with the "Incomplete" status, could we skip the confetti and music?

2023-01-03 17:31 UTC, JoelWiebe approved these changes
Brilliant work!

2023-01-10 16:28 UTC, JoelWiebe commented
This one looks good to me. @Ammar-T can you give this one a quick review when you get a chance?

2023-02-05 16:30 UTC, DCH25 requested changes
small style changes o/w LGTM

2023-02-05 16:30 UTC, DCH25 commented on frontend/src/app/services/todoItem.service.ts
> +  // }
Remove if we're not using it anywhere

2023-02-05 16:30 UTC, DCH25 commented on frontend/src/app/components/todo-list-modal/todo-list-modal.component.scss
> +  padding:0 12px;
nitpick: add spacing

2023-02-05 16:30 UTC, DCH25 commented on frontend/src/app/components/todo-list-modal/todo-list-modal.component.scss
> +  padding:0 12px;
add spacing

2023-02-05 16:30 UTC, DCH25 commented on frontend/src/app/components/todo-item-card-modal/todo-item-card-modal.component.html
> +      <mat-card-subtitle>{{assignee}}</mat-card-subtitle>
spacing

2023-02-13 02:27 UTC, merged