(FIX): Redirect to initial URL upon login
encorelab/ck-board pull request #508
Opened 2023-03-04 03:36 UTC by LunarFang416

## Details

- If a user is not logged into CK-Board and tries to navigate to any url (including embedded urls), they will be redirected to the login page, and after they login, they will be redirected to the URL they originally wanted to go to (if they are authorized to)
- Tested for all embeded URL's (todo, ck-monitor, ck-workspace, board)

- Weird bug for board embeddable URLs was occured when it was running the AuthGuard, it would simultaneously run the BoardGoard and ProjectGuard as well. The AuthGuard would redirect to /login momentarily, but would have a race condition with the BoardGuard, which would then send it to /error since you aren't logged in and can't access API. To quickly remedy this, i added a if statement in BoardGuard and ProjectGuard, to see if the user is logged in, if not it would return false, and the AuthGuard would reroute to /login properly.

Bug:
- To redirect to URL with queryParams, we need to parse them and send it as a separate object to `this.router.navigate`, which it didn't do before.

@JoelWiebe  Could you test this out and see if it works as we want when used in SCORE? It works fine when using it just with CK-Board, so theoretically it should do in SCORE as well.

Closes #505

2023-03-04 18:31 UTC, JoelWiebe requested changes
Thanks for your quick work on this!

- Redirecting to an embedded URL now works great when prompted to login with CK Board
- For some reason, when prompted to log in with SCORE we are still sent to the dashboard

@geoffreykwan had mentioned that SCORE sends the following to CK Board when redirecting with the embedded parameter:

nonce=873b9aaa-878e-429c-9473-c43316a60b78&user-id=1254&username=aa0101&role=student&redirect-url=/project/d5d5c173-8e24-443a-885b-9c953e4e3eea/board/f83f886f-edbe-4998-98fe-e21131b94923?embedded=true

2023-03-04 19:25 UTC, LunarFang416 commented
@JoelWiebe It must be failing to redirect to the original url since `this.userService.redirectUrl` is null after the SSO is successful, because if `this.userService.redirectUrl` is null it redirects to the dashboard, which is happening now.

I don't have SCORE set up right now, so I won't be able to to see how it handles the embeddable url when requested from SCORE.

The backend API does look like it is parsing the `redirect-url` query paramter from the URL, maybe we aren't setting `this.userService.redirectUrl` when the response is returned.

Don't want to create a commit for this, but I think we can try to see if something when we add this line, which will set the `this.userService.redirectUrl` when SSO is successful. This is in the `user.service.ts` file:
```typescript
  async ssoLogin(sso: string | null, sig: string | null): Promise<boolean> {
    return this.http
      .get(`auth/sso/login/${sso}/${sig}`)
      .toPromise()
      .then((result: any) => {
        localStorage.setItem('user', JSON.stringify(result.user));
        localStorage.setItem('access_token', result.token);
        localStorage.setItem('expires_at', result.expiresAt);
        window.location.href = result.redirectUrl;
        this.redirectUrl = result.redirectUrl; // Addition; sets this.userService.redirectUrl after SSO successful
        return true;
      });
  }
```
 @JoelWiebe Could you add this line and see if something changes? 
Not fully confident since I don't have SCORE set up, so might need some help with this

2023-03-04 20:30 UTC, JoelWiebe commented
@LunarFang416 Thanks for the feedback and the suggestion!

Somehow after setting that line, I'm still getting the boot to the project dashboard.

2023-03-04 20:54 UTC, JoelWiebe commented
P.S. @LunarFang416 Here are the file changes that support CK Board authentication: https://github.com/encorelab/ck-board/pull/320/files

If you cannot get this working, no stress, I'll find a workaround for Monday.

2023-03-08 23:36 UTC, geoffreykwan commented
I think I fixed the redirect problem not keeping embedded=true. The way we were parsing the params was splitting on the = character and getting the first value and second value from the split but it doesn't work correctly if there is more than one = character. What we need to do is split on the first = and then get everything before the = as the first value and then everything after the = as the second value.

Before we were ending up with this redirect url (notice embedded at the end does not include =true)
`/project/88d328f8-b5c0-4c3d-95b1-8866226a1aa8/board/c6e30415-6819-4d98-baa1-27f67178f138?embedded`

Now with the fix we end up with this redirect url
`/project/88d328f8-b5c0-4c3d-95b1-8866226a1aa8/board/c6e30415-6819-4d98-baa1-27f67178f138?embedded=true`

I also needed to add a check in the AuthGuard to not redirect to `/login` when SSO is enabled.

2023-03-09 20:22 UTC, JoelWiebe approved these changes
Brilliant! Thank you both for your work @LunarFang416 @geoffreykwan 

LGTM

2023-03-10 03:01 UTC, JoelWiebe commented
@LunarFang416 we should be good to merge!

2023-03-10 03:16 UTC, merged